# Site settings
title: Nags Climate
email: gaddamnagaraju112@gmail.com
description: >
  Personal website of Nagaraju Gaddam — Urban Climate Scientist, Doctoral Researcher, and Entrepreneur. 
  Exploring urban weather extremes, resilience, and data-driven climate innovation for sustainable cities.

twitter_username: nagstweet
github_username: NagsClimate
minimal_mistakes_skin: contrast
search: true

# Branding
logo: "/assets/logos/ng_logo.jpg"
masthead_title: "Nags Climate"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.17.2

# Permalink structure
permalink: /:categories/:title/
paginate: 20
paginate_path: /page:num/
timezone: Europe/Rome

# Include folders
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author details
author:
  name: "Nagaraju Gaddam"
  avatar: "/assets/images/Display pic.JPG"
  bio: >
    Urban Climate Scientist | Doctoral Researcher at University of Bologna <br>
    Exploring climate resilience, extreme weather, and data-driven solutions for cities.
  location: "Bologna, Emilia-Romagna, Italy"
  links:
    - label: "Email"
      icon: "far fa-fw fa-paper-plane"
      url: "mailto:nagaraju.gaddam2@unibo.it"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NagsClimate"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/nagarajugaddam/"

    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/nagstweet"

    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=lRnptscAAAAJ&hl=en"

    - label: "Download CV"
      icon: "far fa-fw fa-file-pdf"
      url: "/assets/files/Nagaraju_Gaddam_CV_2024.pdf"

# Footer links
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/nagstweet"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/NagsClimate"

# Collections (e.g., for projects, portfolio pages)
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

# Default values for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
